# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t8gA4MWG6E39nq2PMPsXV4mtUzmwxYg7
"""

!pip install -q streamlit
import streamlit as st

st.write("Two integer subtraction")

st.header("Subtraction Program")

def user_input(): 
  st.title("Subtraction")
  html_temp="""
  <div style="background-color:black;padding:10x">
  <h style="color:white;text-align:center:">Subtraction of 2 numbers using streamlit</h2>
  </div>"""
  st.markdown(html_temp,unsafe_allow_html=True)
  input1=st.number_input("Give first integer:")
  input2=st.number_input("Give second integer:")
  answer=input1-input2
  st.success("The output is {}".format(answer))
  st.write("CREDIT:21f1003674")